### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by EmaSuriano** [silent-lad/silentlad#1]
Hey Divyansh,
I tried to run your script from the terminal and I received this error message:

``` bash
$ npm i --global silentlad.
npm ERR! code E404
npm ERR! 404 Not Found: silentlad.@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/emanuelsuriano/.npm/_logs/2019-03-07T16_48_49_619Z-debug.log
```

I think it's related with the `publish` for the package.

**Comment by visormatt** [comment]
@EmaSuriano I think it's the `.` in the end of your install command, it should be `npm i --global silentlad` also, I'd avoid installing anything globally `--global` unless absolutely required and you know what the requirement is there for.

**Comment by silent-lad** [comment]
@EmaSuriano chuck the `.` at the end ..and yea use npx as @visormatt said.
